baseURL = "http://example.org/"
languageCode = "en-us"
title = "John, Complected"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 10 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[params]
  show_reading_time = true
  favicon = ""
  site_logo = ""
  description = "Herein are the ramblings on tech, life and study of John. Father to three, outnumbered in a house full or women. Most of what is wrtten here is unlikely to be helpful, though hopefully it can be ammusing."
  facebook = ""
  twitter = "https://twitter.com/IJYIJohn"
  instagram = ""
  youtube = ""
  github = "john-nicholson"
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 2